### ISSUE TITLE
Scrolling over Armor with JEI installed

### ISSUE THREAD

**Issue by Versimno** [SilentChaos512/Equipment-Tooltips#1]
### Versions

Minecraft Version: 1.12.2
Minecraft Forge Version: 14.23.3.2655
Equipment Tooltips Version: 1.0.0-1
Silent Lib Version: 2.3.1-107
Just Enough Items Version: 4.9.1.182

### Expected behavior

- Armor shows whether or not it's better than what is equipped, along with all it's stats

### Actual behaviour

- Minecraft crashes as soon as the item is scrolled over in JEI

### Crash Report

- https://paste.dimdev.org/zanivisefe.txt

### Steps to reproduce the problem

1. Open any inventory
2. Scroll over any armor
3. Crash

**Comment by SilentChaos512** [comment]
Just encountered this myself. I'll have the fixed version up soon.
