### ISSUE TITLE
Crash when hovering over Repurpose's sickles

### ISSUE THREAD

**Issue by Versimno** [SilentChaos512/Equipment-Tooltips#3]
### Versions

Minecraft Version: 1.12.2
Forge Version: 14.23.3.2655
Equipment Tooltips Version: 1.0.2-3
Silent Lib Version: 2.3.1-107
Repurpose Version: 1.0.0.18

### Expected behavior

- Displays the stats of the sickle

### Actual behaviour

- Crashes

### Steps to reproduce the problem

1. Hover over a sickle

### Crash Report

https://paste.dimdev.org/emesosirax.txt

**Comment by SilentChaos512** [comment]
Please report to Repurpose, this would be best fixed on their end.

**Comment by Versimno** [comment]
They'll fix it soon. ty
