### ISSUE TITLE
Crash after killing a squid

### ISSUE THREAD

**Issue by NielsPilgaard** [SilentChaos512/Equipment-Tooltips#5]
### Versions

Minecraft Version: 1.14.4
EquipmentTooltips-1.14.4-1.3.2+10
SilentLib-1.14.4-4.4.0+44
mysticalworld-1.14.4-1.6.0
mysticallib-1.14.4-1.5

### Expected behavior

- Killing a squid results in a dead squid.

### Actual behaviour

- Killing a squid results in a crash.

### Steps to reproduce the problem

1. Make an instance with both Mystical World and Equipment Tooltips
2. Kill a squid
3. ...
4. Profit

I suspect that this crash is caused by a bad interaction between Mystical World and Equipment Tooltips, which is why I mentioned both version further up. I have repoted this issue on both trackers.

Original report: https://github.com/NillerMedDild/Enigmatica4/issues/93

**Comment by noobanidus** [comment]
Yes, this is rather confusing. It appears to be saying that the getEnchantability method is abstract/not-implemented but I fail to see how this is possible...

**Comment by noobanidus** [comment]
Yep, this was entirely my fault and we're not going to talk about it. I could blame it on Java double-inheritance but it's ... entirely my fault. Feel free to close the issue, as I've resolved it in the recently release 1.6.1 version of Mystical World.
